import { Hono } from "hono";
import type { Env } from "../types";

const ui = new Hono<{ Bindings: Env }>();

ui.get("/", (c) => c.html(String.raw`<!doctype html>
<html lang="fa" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>دایرکتوری پزشکان</title><style>
:root{font-family:Tahoma,Arial,sans-serif;color:#172033;background:#f4f7fb;line-height:1.8}*{box-sizing:border-box}body{margin:0}.shell{max-width:1100px;margin:auto;padding:24px}.hero{background:linear-gradient(135deg,#123b5d,#168a8a);color:white;border-radius:24px;padding:28px;margin-bottom:18px;box-shadow:0 12px 30px #123b5d22}.hero h1{margin:0 0 6px;font-size:clamp(24px,4vw,40px)}.hero p{margin:0;color:#d9f6f1}.nav{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.nav button,.button{border:0;border-radius:12px;padding:10px 16px;background:#0e7c7b;color:white;cursor:pointer;font:inherit}.nav button{background:white;color:#0e5f63}.nav button.active{background:#0e7c7b;color:white}.panel{background:white;border-radius:18px;padding:20px;margin-bottom:16px;box-shadow:0 5px 18px #17203312}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}label{display:block;font-size:14px;color:#536174}input,textarea,select{width:100%;border:1px solid #d9e1eb;border-radius:10px;padding:10px;margin-top:4px;font:inherit;background:#fbfcfe}textarea{min-height:90px}.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:14px}.muted{color:#68768a;font-size:14px}.message{padding:10px 12px;border-radius:10px;background:#eef7f6;margin:10px 0;display:none}.message.show{display:block}.error{background:#fff0f0;color:#a33434}.doctor-card{border:1px solid #e3eaf2;border-radius:14px;padding:14px}.doctor-card h3{margin:0 0 4px}.tag{display:inline-block;background:#edf5f5;color:#176b6c;padding:2px 8px;border-radius:99px;font-size:12px;margin:2px}.hidden{display:none}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:9px;border-bottom:1px solid #e9eef4;text-align:right;font-size:14px}.logout{background:#8b3d50}.status{font-weight:bold}
</style><style>
body{background:radial-gradient(circle at top right,#e4f5f2 0,#f4f7fb 38%,#eef2f8 100%)}.shell{max-width:1180px}.hero{position:relative;overflow:hidden;background:linear-gradient(120deg,#0d334f 0%,#126b76 55%,#25a28f 100%);padding:34px}.hero:after{content:"";position:absolute;width:260px;height:260px;border:35px solid #ffffff14;border-radius:50%;left:-80px;top:-120px}.hero h1{letter-spacing:-1px}.hero-meta{position:relative;z-index:1;display:flex;justify-content:space-between;align-items:center;gap:14px;margin-top:20px;flex-wrap:wrap}.user-chip{background:#ffffff18;border:1px solid #ffffff30;border-radius:999px;padding:6px 13px;font-size:13px}.nav{position:sticky;top:10px;z-index:3;background:#ffffffd9;backdrop-filter:blur(12px);padding:8px;border:1px solid #ffffff;border-radius:16px;box-shadow:0 8px 24px #17304b12}.nav button{font-size:14px}.panel{border:1px solid #e5ebf2}.panel>h2{margin-top:0;color:#123b5d}.section-head{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.profile-head{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:16px;padding:14px;background:#f5faf9;border:1px solid #dcefeb;border-radius:16px;margin-bottom:20px}.avatar{width:74px;height:74px;border-radius:22px;object-fit:cover;background:linear-gradient(135deg,#d5efeb,#b7d7e6);display:grid;place-items:center;color:#176b6c;font-size:28px;font-weight:bold}.profile-head h3{margin:0}.profile-head p{margin:3px 0 0;color:#68768a;font-size:13px}.card-preview{background:linear-gradient(135deg,#123b5d,#199287);color:white;border-radius:16px;padding:14px;min-width:230px;max-width:280px;box-shadow:0 8px 20px #123b5d25}.card-preview strong{display:block;font-size:16px}.card-preview small{color:#d6f6f0}.empty{padding:20px;text-align:center;color:#78879a;background:#f8fafc;border-radius:14px}.danger{background:#9a4053!important}.button.secondary{background:#e8f1f4;color:#17656a}.button:disabled{opacity:.6;cursor:wait}@media(max-width:680px){.shell{padding:12px}.hero{padding:24px 18px;border-radius:18px}.nav{top:4px}.nav button{flex:1 1 42%;padding:8px 6px}.profile-head{grid-template-columns:auto 1fr}.card-preview{grid-column:1/-1;max-width:none}.panel{padding:15px}}
</style></head><body><main class="shell"><section class="hero"><h1>دایرکتوری پزشکان</h1><p>فضای خصوصی برای ارتباط، معرفی و نگهداری اطلاعات پزشکان گروه</p><div class="hero-meta"><span class="user-chip" id="heroStatus">برای شروع وارد شوید</span><span class="user-chip">نسخه‌ی توسعه · DEBUG_MODE</span></div></section>
<nav class="nav"><button data-tab="login">ورود با OTP</button><button data-tab="directory">فهرست پزشکان</button><button data-tab="profile">پروفایل من</button><button data-tab="referrals">معرفی‌نامه‌ها</button><button data-tab="admin">پنل مدیریت</button><button id="logout" class="logout">خروج</button></nav>
<div id="message" class="message"></div><section class="grid quick-stats"><article class="panel"><span class="muted">دسترسی</span><strong id="accessStat">مهمان</strong><small>اطلاعات عمومی پزشکان</small></article><article class="panel"><span class="muted">ورود</span><strong id="loginStat">وارد نشده</strong><small>برای دیدن اطلاعات بیشتر وارد شوید</small></article><article class="panel"><span class="muted">راهنما</span><strong>۵ دقیقه</strong><small>اعتبار کد OTP</small></article></section>
<section id="tab-login" class="tab panel"><h2>ورود</h2><p class="muted">در حالت DEBUG_MODE کد OTP در همین صفحه نمایش داده می‌شود.</p><div class="grid"><label>شماره موبایل<input id="phone" placeholder="09121234567" inputmode="tel"></label><label>کد OTP<input id="code" placeholder="کد شش رقمی" inputmode="numeric"></label></div><div class="actions"><button class="button" id="requestOtp">دریافت کد</button><button class="button" id="verifyOtp">تأیید و ورود</button><span id="otpHint" class="muted"></span></div></section>
<section id="tab-directory" class="tab panel hidden"><div class="actions"><input id="search" placeholder="جست‌وجو بر اساس نام"><button class="button" id="loadDoctors">بارگذاری فهرست</button></div><div id="doctorList" class="grid" style="margin-top:14px"></div></section>
<section id="tab-referrals" class="tab panel hidden"><h2>معرفی‌نامه‌ها</h2><div class="grid"><label>نام پزشک<input id="refName"></label><label>تخصص<input id="refSpecialty"></label><label>شهر<input id="refCity"></label><label>تلفن<input id="refPhone"></label></div><label style="margin-top:12px">توضیحات<textarea id="refNotes"></textarea></label><div class="actions"><button class="button" id="addReferral">ثبت معرفی</button><button class="button" id="loadReferrals">بارگذاری معرفی‌ها</button></div><div id="referralList" class="grid" style="margin-top:12px"></div></section>
<section id="tab-profile" class="tab panel hidden"><h2>پروفایل من</h2><p id="profileStatus" class="muted">ابتدا وارد شوید.</p><div class="grid"><label>نام و نام خانوادگی<input id="fullName"></label><label>تخصص<input id="specialtyMain"></label><label>شهر<input id="city"></label><label>شماره عمومی<input id="phonePublic"></label><label>شماره نظام پزشکی<input id="council"></label><label>ایمیل<input id="email" type="email"></label></div><label style="margin-top:12px">درباره پزشک<textarea id="bio"></textarea></label><div class="actions"><button class="button" id="saveProfile">ذخیره پروفایل</button></div><hr><h3>محل‌های کار</h3><div class="grid"><label>نام محل کار<input id="locationName"></label><label>آدرس<input id="locationAddress"></label></div><button class="button" id="addLocation" style="margin-top:10px">افزودن محل کار</button><div id="locations" class="grid" style="margin-top:12px"></div><hr><h3>شبکه اجتماعی</h3><div class="grid"><label>پلتفرم<input id="socialPlatform" placeholder="instagram"></label><label>لینک یا مقدار<input id="socialValue"></label><label>نمایش<select id="socialVisibility"><option value="public">عمومی</option><option value="members">اعضا</option><option value="private">خصوصی</option></select></label></div><button class="button" id="addSocial" style="margin-top:10px">افزودن لینک</button><div id="socials" class="grid" style="margin-top:12px"></div><hr><h3>فیلد اضافه</h3><div class="grid"><label>نام فیلد<input id="fieldKey" placeholder="زبان‌ها"></label><label>مقدار<input id="fieldValue"></label><label>نمایش<select id="fieldVisibility"><option value="members">اعضا</option><option value="public">عمومی</option><option value="private">خصوصی</option></select></label></div><button class="button" id="addField" style="margin-top:10px">افزودن فیلد</button><div id="fields" class="grid" style="margin-top:12px"></div></section>
<section id="tab-admin" class="tab panel hidden"><h2>پنل مدیریت</h2><p class="muted">این بخش فقط برای توکن ادمین کار می‌کند.</p><div class="actions"><select id="adminStatus"><option value="pending">در انتظار</option><option value="approved">تأییدشده</option><option value="rejected">ردشده</option><option value="">همه</option></select><input id="adminSearch" placeholder="نام یا شماره"><button class="button" id="loadAdmin">بارگذاری</button></div><div id="adminList" style="overflow:auto;margin-top:12px"></div></section>
</main><script>
const $=id=>document.getElementById(id);let token=localStorage.getItem('dd_token')||'';let me={doctorId:localStorage.getItem('dd_doctor_id')||''};
function msg(text,error=false){$('message').textContent=text;$('message').className='message show'+(error?' error':'');setTimeout(()=>$('message').className='message',5000)}
async function api(path,opt={}){opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});if(token)opt.headers.Authorization='Bearer '+token;let r=await fetch(path,opt);let data=await r.json().catch(()=>({error:'پاسخ نامعتبر'}));if(!r.ok)throw new Error(data.error||'خطا');return data}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$('tab-'+b.dataset.tab).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.tab==='directory')loadDoctors();if(b.dataset.tab==='profile')loadProfile();if(b.dataset.tab==='referrals')loadReferrals();if(b.dataset.tab==='admin')loadAdmin()});
$('requestOtp').onclick=async()=>{try{let d=await api('/api/auth/request-otp',{method:'POST',body:JSON.stringify({phone:$('phone').value})});$('otpHint').textContent=d.debugCode?'کد آزمایشی: '+d.debugCode:'پیامک ارسال شد';msg('کد ورود آماده است')}catch(e){msg(e.message,true)}};
$('verifyOtp').onclick=async()=>{try{let d=await api('/api/auth/verify-otp',{method:'POST',body:JSON.stringify({phone:$('phone').value,code:$('code').value})});token=d.token;me=d;localStorage.setItem('dd_token',token);localStorage.setItem('dd_doctor_id',d.doctorId);msg('ورود موفق بود؛ وضعیت: '+d.status);document.querySelector('[data-tab="profile"]').click()}catch(e){msg(e.message,true)}};
async function loadDoctors(){try{let d=await api('/api/doctors?q='+encodeURIComponent($('search').value));$('doctorList').innerHTML=d.doctors.map(x=>'<article class="doctor-card"><h3>'+x.full_name+'</h3><div>'+([x.specialty_main,x.city].filter(Boolean).join(' · ')||'بدون اطلاعات')+'</div><span class="tag">'+(x.phone_public||'شماره عمومی ثبت نشده')+'</span></article>').join('')||'<p>موردی پیدا نشد.</p>'}catch(e){msg(e.message,true)}}$('loadDoctors').onclick=loadDoctors;
async function loadReferrals(){try{let d=await api('/api/referrals');$('referralList').innerHTML=d.referrals.map(x=>'<article class="doctor-card"><h3>'+x.recommended_name+'</h3><div>'+([x.specialty,x.city].filter(Boolean).join(' · ')||'بدون دسته‌بندی')+'</div><p>'+ (x.notes||'')+'</p></article>').join('')||'<p>موردی ثبت نشده.</p>'}catch(e){msg(e.message,true)}}$('loadReferrals').onclick=loadReferrals;
$('addReferral').onclick=async()=>{try{await api('/api/referrals',{method:'POST',body:JSON.stringify({recommendedName:$('refName').value,specialty:$('refSpecialty').value,city:$('refCity').value,phone:$('refPhone').value,notes:$('refNotes').value})});msg('معرفی‌نامه ثبت شد');loadReferrals()}catch(e){msg(e.message,true)}};
async function loadProfile(){if(!token){$('profileStatus').textContent='برای تکمیل پروفایل ابتدا وارد شوید.';return}try{let d=await api('/api/doctors/me/profile');$('profileStatus').textContent='وضعیت: '+(d.status||'approved');$('fullName').value=d.full_name||'';$('specialtyMain').value=d.specialty_main||'';$('city').value=d.city||'';$('phonePublic').value=d.phone_public||'';$('council').value=d.medical_council_number||'';$('email').value=d.email||'';$('bio').value=d.bio||'';$('locations').innerHTML=(d.workLocations||[]).map(x=>'<div class="doctor-card">'+x.location_name+'<br><span class="muted">'+(x.address||'')+'</span><br><button class="button logout" onclick="removeItem(\'/api/doctors/me/work-locations/'+x.id+'\',loadProfile)">حذف</button></div>').join('');$('socials').innerHTML=(d.socialLinks||[]).map(x=>'<div class="doctor-card">'+x.platform+': '+x.value+'<br><button class="button logout" onclick="removeItem(\'/api/doctors/me/social-links/'+x.id+'\',loadProfile)">حذف</button></div>').join('');$('fields').innerHTML=(d.extraFields||[]).map(x=>'<div class="doctor-card">'+x.field_key+': '+x.field_value+'</div>').join('')}catch(e){msg(e.message,true)}}
$('saveProfile').onclick=async()=>{try{await api('/api/doctors/me/profile',{method:'PUT',body:JSON.stringify({fullName:$('fullName').value,specialtyMain:$('specialtyMain').value,city:$('city').value,phonePublic:$('phonePublic').value,medicalCouncilNumber:$('council').value,email:$('email').value,bio:$('bio').value})});msg('پروفایل ذخیره شد');loadProfile()}catch(e){msg(e.message,true)}};
$('addLocation').onclick=async()=>{try{await api('/api/doctors/me/work-locations',{method:'POST',body:JSON.stringify({locationName:$('locationName').value,address:$('locationAddress').value})});$('locationName').value='';$('locationAddress').value='';loadProfile()}catch(e){msg(e.message,true)}};
$('addSocial').onclick=async()=>{try{await api('/api/doctors/me/social-links',{method:'POST',body:JSON.stringify({platform:$('socialPlatform').value,value:$('socialValue').value,visibility:$('socialVisibility').value})});loadProfile()}catch(e){msg(e.message,true)}};
$('addField').onclick=async()=>{try{await api('/api/doctors/me/extra-fields',{method:'POST',body:JSON.stringify({key:$('fieldKey').value,value:$('fieldValue').value,visibility:$('fieldVisibility').value})});loadProfile()}catch(e){msg(e.message,true)}};
async function removeItem(path,done){try{await api(path,{method:'DELETE'});done()}catch(e){msg(e.message,true)}}
async function loadAdmin(){try{let q=new URLSearchParams();if($('adminStatus').value)q.set('status',$('adminStatus').value);if($('adminSearch').value)q.set('q',$('adminSearch').value);let d=await api('/api/admin/doctors?'+q);$('adminList').innerHTML='<table class="table"><tr><th>نام</th><th>شماره</th><th>وضعیت</th><th>عملیات</th></tr>'+d.doctors.map(x=>'<tr><td>'+x.full_name+'</td><td>'+x.phone+'</td><td>'+x.status+'</td><td>'+(x.status==='pending'?'<button class="button" onclick="adminAction(\'/api/admin/approve/'+x.id+'\')">تأیید</button> <button class="button logout" onclick="adminAction(\'/api/admin/reject/'+x.id+'\')">رد</button>':'')+'</td></tr>').join('')+'</table>'}catch(e){msg(e.message,true)}}
async function adminAction(path){try{await api(path,{method:'POST'});loadAdmin();msg('عملیات انجام شد')}catch(e){msg(e.message,true)}}$('loadAdmin').onclick=loadAdmin;$('logout').onclick=()=>{localStorage.removeItem('dd_token');localStorage.removeItem('dd_doctor_id');token='';me={doctorId:''};msg('خارج شدی')};document.querySelector('[data-tab="login"]').click();
</script></body></html>`));

export default ui;
